apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifelink-backend
  labels:
    app: lifelink
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lifelink
      component: backend
  template:
    metadata:
      labels:
        app: lifelink
        component: backend
    spec:
      containers:
      - name: backend
        image: lifelink/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: lifelink-secrets
              key: mongodb-url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: lifelink-config
              key: redis-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: lifelink-secrets
              key: secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: lifelink-secrets
              key: openai-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: lifelink-backend
  labels:
    app: lifelink
    component: backend
spec:
  selector:
    app: lifelink
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
